### GET SWAGGER
GET http://localhost:8080/api-docs   HTTP/1.1


### GET ALL ITEMS
GET http://localhost:8080/ HTTP/1.1


### GET ITEM
GET http://localhost:8080/646f771bcd31301f3d48ca3b HTTP/1.1



### POST NEW ITEM TO THE LIST
POST  http://localhost:8080/   HTTP/1.1
content-type: application/json

{
    "item": "swipe the floor"
}


### EDIT ITEM
PUT http://localhost:8080/646f8e927c8d5abf6c010ba7 HTTP/1.1
content-type: application/json

{
    "item": "wash the ..."
}

### DELETE ITEM
DELETE http://localhost:8080/646f8e927c8d5abf6c010ba7 HTTP/1.1