### GET SWAGGER
GET http://localhost:8080/api-docs   HTTP/1.1


### GET ALL ITEMS
GET http://localhost:8080/ HTTP/1.1


### GET ITEM
GET http://localhost:8080/64701232473609f0f1bddcc4 HTTP/1.1



### POST NEW ITEM TO THE LIST
POST  http://localhost:8080/   HTTP/1.1
content-type: application/json

{
    "item": 345
}


### EDIT ITEM the id has 24 characters
PUT http://localhost:8080/646fe4f970e2b9d63f33c HTTP/1.1 
content-type: application/json

{
    "item": "wash the something"
}

### DELETE ITEM
DELETE http://localhost:8080/646feeb35efcfa64b5f HTTP/1.1